---
- hosts: webservers 
  become: True
  tasks:
    - name: Install packages
      yum: #this is for redhat for ubuntu use apt
        name: "httpd"
        state: "present"
    - name: Start Apache server
      service:
        name: httpd
        state: started
        enabled: True
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
...
