apiVersion: v1
kind: Service
metadata:
  name: cicd-app
spec:
  selector:
    app: cicd-app
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080  # Assuming your app runs on port 3000
  type: NodePort  # Expose the service outside the cluster





# apiVersion: v1

# kind: Service
# metadata:
#   name: medicure-service
# spec:
#   type: NodePort
#   selector:
#     app: front-end
#   ports:
#     - protocol: TCP
#       port: 8082
#       targetPort: http-web-app-01
